<p class="ec-headerOutsetRole__text">About 10,000 types of vacuum components in stock at all times.<span class="ec-headerOutsetRole__textSub">Business Hours： 9:00-18:00, excluding weekends and holidays</span></p>

<div class="ec-headerOutsetRole__inner">
                                                <p class="ec-headerOutsetRole__text">About 10,000 types of vacuum components in stock at all times.<span class="ec-headerOutsetRole__textSub">Business Hours： 9:00-18:00, excluding weekends and holidays</span></p>
                                <ul class="ec-headerOutsetRole__nav">
                    
                                        <li class="ec-headerOutsetRole__navItem">
                        <b aria-hidden="true" class="iconfont iconfont-laptop-list"></b>
                        Number of Products Listed 27,553items
                    </li>

                                        <li class="ec-headerOutsetRole__navItem">
                        <b aria-hidden="true" class="iconfont iconfont-phone-volume"></b>
                        <span>Tokyo 03-3270-5761</span>
                        <span>Osaka 06-6131-4751</span>
                    </li>

                                        <li class="ec-headerOutsetRole__navItem">
                        <a href="https://en.cosmotec-co.jp/contact">
                            <b aria-hidden="true" class="iconfont iconfont-comment-dots"></b>
                            Contact Us
                        </a>
                    </li>

                    <li class="ec-headerOutsetRole__navItem">
                                                <a href="https://en.cosmotec-co.jp/info/faq/">
                            <b aria-hidden="true" class="iconfont iconfont-question-circle"></b>
                            FAQ
                            <b aria-hidden="true" class="iconfont iconfont-angle-down-small"></b>
                        </a>

                        <div class="ec-headerOutsetRole__subnav">
                            <ul class="ec-headerOutsetRole__subnavList">
                                                                <li class="ec-headerOutsetRole__subnavItem">
                                    <a href="https://en.cosmotec-co.jp/info/client/">
                                        Which trading company can I do business with?
                                    </a>
                                </li>

                                                                <li class="ec-headerOutsetRole__subnavItem">
                                    <a href="https://en.cosmotec-co.jp/info/faq/#with_trading">
                                        Can I pay for this at the public expense?
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="ec-headerOutsetRole__navItem ec-headerOutsetRole__language">
                        <button type="button" class="ec-btn">
                            <b aria-hidden="true" class="iconfont iconfont-globe"></b>
                            <b aria-hidden="true" class="iconfont iconfont-angle-down-small"></b>
                        </button>
                        <div class="ec-headerOutsetRole__subnav" data-sys-env="prod">
                            <ul class="ec-headerOutsetRole__subnavList">
                                <li class="ec-headerOutsetRole__subnavItem">
                                    <button type="button" class="ec-btn js-change-japanese">日本語</button>
                                </li>
                                <li class="ec-headerOutsetRole__subnavItem">
                                    <button type="button" class="ec-btn js-change-english">English</button>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>