<div class="ec-layoutRole__header--multiple">
    <header>
        <div class="ec-headerOutsetRole">
            <div class="ec-headerOutsetRole__inner">
                                                <p class="ec-headerOutsetRole__text">About 10,000 types of vacuum components in stock at all times.<span class="ec-headerOutsetRole__textSub">Business Hours： 9:00-18:00, excluding weekends and holidays</span></p>
                                <ul class="ec-headerOutsetRole__nav">
                    
                                        <li class="ec-headerOutsetRole__navItem">
                        <b aria-hidden="true" class="iconfont iconfont-laptop-list"></b>
                        Number of Products Listed 27,553items
                    </li>

                                        <li class="ec-headerOutsetRole__navItem">
                        <b aria-hidden="true" class="iconfont iconfont-phone-volume"></b>
                        <span>Tokyo 03-3270-5761</span>
                        <span>Osaka 06-6131-4751</span>
                    </li>

                                        <li class="ec-headerOutsetRole__navItem">
                        <a href="#contact">
                            <b aria-hidden="true" class="iconfont iconfont-comment-dots"></b>
                            Contact Us
                        </a>
                    </li>

                    <li class="ec-headerOutsetRole__navItem">
                                                <a href="#info/faq/">
                            <b aria-hidden="true" class="iconfont iconfont-question-circle"></b>
                            FAQ
                            <b aria-hidden="true" class="iconfont iconfont-angle-down-small"></b>
                        </a>

                        <div class="ec-headerOutsetRole__subnav">
                            <ul class="ec-headerOutsetRole__subnavList">
                                                                <li class="ec-headerOutsetRole__subnavItem">
                                    <a href="#info/client/">
                                        Which trading company can I do business with?
                                    </a>
                                </li>

                                                                <li class="ec-headerOutsetRole__subnavItem">
                                    <a href="#info/faq/#with_trading">
                                        Can I pay for this at the public expense?
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="ec-headerOutsetRole__navItem ec-headerOutsetRole__language">
                        <button type="button" class="ec-btn">
                            <b aria-hidden="true" class="iconfont iconfont-globe"></b>
                            <b aria-hidden="true" class="iconfont iconfont-angle-down-small"></b>
                        </button>
                        <div class="ec-headerOutsetRole__subnav" data-sys-env="prod">
                            <ul class="ec-headerOutsetRole__subnavList">
                                <li class="ec-headerOutsetRole__subnavItem">
                                    <button type="button" class="ec-btn js-change-japanese">日本語</button>
                                </li>
                                <li class="ec-headerOutsetRole__subnavItem">
                                    <button type="button" class="ec-btn js-change-english">English</button>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="ec-headerNaviRole--multiple ">

                        <div class="ec-headerNaviRole__left">
                <a href="/" class="ec-headerRole__logo">
                                            <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/common/cosmotec.svg" alt="If the vacuum parts mail order Cosmo Tech">
                                    </a>
            </div>

                        <div class="ec-headerNaviRole__search">
                <form action="/products/list">
                    <div class="ec-headerNaviRole__searchInner">
                        <div class="ec-headerSearch" id="ec-headerSearch">
                            <div class="ec-headerSearch__keyword">
                                <div class="ec-input">

                                    <input type="search" class="ec-headerSearch__keywordInput--sp" id="ec-headerSearch__keywordInput--sp" name="search_keywords--sp" placeholder="Looking for any product?" value="" autocomplete="off">
                                    <input type="search" class="ec-headerSearch__keywordInput" id="ec-headerSearch__keywordInput" name="search_keywords" placeholder="Looking for any product? (Keyword, product name, Part No.)" value="" autocomplete="off">

                                    <button type="reset" class="ec-headerSearch__keywordReset" id="ec-headerSearch__keywordReset">
                                        <b aria-hidden="true" class="iconfont iconfont-times-circle"></b>
                                    </button>
                                    <button class="ec-blockBtn--action js-search-submit is-pe-none" type="submit">
                                        <b aria-hidden="true" class="iconfont iconfont-search"></b>
                                    </button>

                                    <div class="ec-headerSearchCont" id="ec-headerSearchCont">

                                                                                <div id="js-product-section" class="ec-headerSearchCont__suggest is-hidden">
                                            <ul id="js-add-product" class="ec-headerSearchCont__suggestList">
                                                                                            </ul>
                                        </div>

                                                                                <div class="ec-headerSearchCont__suggest">
                                                                                        <div id="js-searchHistory-section-not-entered">
                                                <div class="ec-headerSearchCont__heading"><span class="ec-headerSearchCont__headingItem"><b aria-hidden="true" class="iconfont iconfont-clock-history"></b>Search History</span></div>
                                                <ul id="js-add-search-history-not-entered" class="ec-headerSearchCont__suggestList">
                                                                                                    <li class="ec-headerSearchCont__suggestItem"><a href="#products/list?search_keywords--sp=&amp;search_keywords=VG20&amp;keyword=VG20" class="ec-headerSearchCont__suggestLink"><b aria-hidden="true" class="iconfont iconfont-clock-history"></b>VG20</a></li></ul>
                                            </div>

                                                                                        <div id="js-searchHistory-section-word" class="ec-headerSearchCont__heading is-hidden">
                                                <span class="ec-headerSearchCont__headingItem">Keyword Candidate</span>
                                                <span class="ec-headerSearchCont__headingItem"><b aria-hidden="true" class="iconfont iconfont-clock-history"></b>Search History</span>
                                            </div>

                                                                                        <div id="js-searchTag-section" class="is-hidden">
                                                <ul id="js-add-searchTag" class="ec-headerSearchCont__suggestList">
                                                                                                    </ul>
                                            </div>


                                                                                        <div id="js-searchHistory-section" class="is-hidden">
                                                <ul id="js-add-search-history" class="ec-headerSearchCont__suggestList">
                                                                                                    </ul>
                                            </div>
                                        </div>

                                                                                <div id="js-category-section" class="ec-productCategory is-hidden">
                                            <div class="ec-productCategory__heading--sub">Category </div>
                                            <ul id="js-add-category" class="ec-productCategory__list">
                                                                                            </ul>
                                        </div>

                                                                                <div id="js-item-section" class="ec-productCategory is-hidden">
                                            <div class="ec-productCategory__heading--sub">Subcategory</div>
                                            <ul id="js-add-item" class="ec-productCategory__list">
                                                                                            </ul>
                                        </div>

                                                                                <div id="js-sp-display-show-category" class="is-hidden">
                                            <div class="ec-productCategory__heading">Product Category</div>
                                            <ul class="ec-productCategory__list">
                                                <li class="ec-productCategory__item">
                                                    <a href="/feedthrough/coaxial/coaxial-bnc-type.html" class="ec-productCategory__link">
                                                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_001.jpg" alt="Feedthrough">
                                                        Feedthrough
                                                    </a>
                                                </li>

                                                <li class="ec-productCategory__item">
                                                    <a href="#products/list?category_id=2" class="ec-productCategory__link">
                                                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_002.jpg" alt="Isolator">
                                                        Isolator
                                                    </a>
                                                </li>

                                                                                                <li class="ec-productCategory__item">
                                                    <a href="#products/list?category_id=3" class="ec-productCategory__link">
                                                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_003.jpg" alt="Viewport">
                                                        Viewport
                                                    </a>
                                                </li>

                                                                                                <li class="ec-productCategory__item">
                                                    <a href="#products/list?category_id=4" class="ec-productCategory__link">
                                                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_004.jpg" alt="Vacuum Component">
                                                        Vacuum Component
                                                    </a>
                                                </li>

                                                                                                <li class="ec-productCategory__item">
                                                    <a href="#products/list?category_id=5" class="ec-productCategory__link">
                                                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_005.jpg" alt="Vacuum Valve">
                                                        Vacuum Valve
                                                    </a>
                                                </li>

                                                                                                <li class="ec-productCategory__item">
                                                    <a href="#products/list?category_id=383" class="ec-productCategory__link">
                                                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_006.jpg" alt="Motion Feedthroughs">
                                                        Motion Feedthroughs
                                                    </a>
                                                </li>

                                                                                                <li class="ec-productCategory__item">
                                                    <a href="#products/list?category_id=7" class="ec-productCategory__link">
                                                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_007.jpg" alt="Others">
                                                        Others
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>

                                                        <div class="ec-headerSearchCont__side" id="ec-headerSearchCont__side">
                                                                <div id="js-product-side" class="ec-productDetail">
                                                                    </div>

                                                                <div id="js-search-tag-sub-category-side" class="ec-productCategory__side">
                                    <div id="js-search-tag-sub-category-side-heading" class="ec-productCategory__sideHeading">Subcategory
                                                                            </div>
                                    <ul id="js-add-search-tag-sub-category-side-list" class="ec-productCategory__sideList">
                                                                            </ul>
                                </div>

                                                                <div id="js-search-tag-category-side" class="ec-productCategory__side">
                                    <div id="js-search-tag-category-side-heading" class="ec-productCategory__sideHeading">Category 
                                                                            </div>
                                    <ul id="js-add-search-tag-category-side-list" class="ec-productCategory__sideList">
                                                                            </ul>
                                </div>

                                                                <div id="js-sub-category-side" class="ec-productCategory__side">
                                    <div id="js-sub-category-side-heading" class="ec-productCategory__sideHeading">Subcategory
                                                                            </div>
                                    <ul id="js-add-sub-category-side-list" class="ec-productCategory__sideList">
                                                                            </ul>
                                </div>

                                                                <div id="js-category-side" class="ec-productCategory__side">
                                    <div id="js-category-side-heading" class="ec-productCategory__sideHeading">Category 
                                                                            </div>
                                    <ul id="js-add-category-side-list" class="ec-productCategory__sideList">
                                                                            </ul>
                                </div>
                            </div>

                            <div class="ec-headerSearch__close" id="ec-headerSearch__close">
                                <b aria-hidden="true" class="iconfont iconfont-times"></b>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div class="ec-headerNaviRole__right">
                    <div class="ec-headerNaviRole__nav">
                        <div class="ec-headerNav">
                                                        <div class="ec-headerUser" data-gtm-vis-recent-on-screen9228359_32="56" data-gtm-vis-first-on-screen9228359_32="56" data-gtm-vis-total-visible-time9228359_32="100" data-gtm-vis-has-fired9228359_32="1">
                                                                <span class="ec-headerUser__sub">Mr./Ms.</span>
                                                                                                    小池 茂明
                                                                                            </div>

                                                        <div class="ec-headerMypage">
                                <a href="#mypage/">My Account</a>
                                <div class="ec-headerMypage__subnav">
                                    <ul class="ec-headerMypage__subnavList">
                                                                                <li class="ec-headerMypage__subnavItem">
                                            <a href="#mypage/history_list">Order History</a>
                                        </li>

                                                                                <li class="ec-headerMypage__subnavItem">
                                            <a href="#mypage/estimate_list">Quote History</a>
                                        </li>

                                                                                <li class="ec-headerMypage__subnavItem">
                                            <a href="#mypage/change">Registered Information</a>
                                        </li>

                                                                                <li class="ec-headerMypage__subnavItem">
                                            <a href="#mypage/wishlist">My List</a>
                                        </li>

                                                                                <li class="ec-headerMypage__subnavItem">
                                            <a href="#mypage/delivery">Edit Address Book</a>
                                        </li>

                                                                                <li class="ec-headerMypage__subnavItem">
                                            <a href="#logout">Sign out</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                            <ul class="ec-headerNav__list">
                                                                <li class="ec-headerNav__item">
                                    <a href="#mypage/wishlist" class="ec-headerNav__itemLink">My List</a>
                                </li>

                                                                <li class="ec-headerNav__item">
                                    <a href="#mypage/estimate_list" class="ec-headerNav__itemLink">Quote History</a>
                                </li>

                                                                <li class="ec-headerNav__item">
                                    <a href="#mypage/history_list" class="ec-headerNav__itemLink">Order History</a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="ec-headerRole__search" id="ec-headerRole__search"><b aria-hidden="true" class="iconfont iconfont-search"></b></div>
                    <div class="ec-headerRole__cart">
                        <div class="ec-cartNaviWrap">
                            <a href="#cart">
                                <div class="ec-cartNavi">
                                    <b aria-hidden="true" class="iconfont iconfont-shopping-cart"></b>
                                    <span class="ec-cartNavi__badge is-active">2</span>
                                    <div class="ec-cartNavi__label">
                                        <div class="ec-cartNavi__price">
                                            3,908,960 JPY<span class="ec-cartNavi__priceSub">(With Tax)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>

                    <div class="ec-headerRole__navSP">
                        <div class="ec-headerNavSP"><b aria-hidden="true" class="iconfont iconfont-bars"></b></div>
                    </div>
                </div>

            
        </div>
    </header>
</div>





















<div class="ec-categoryNaviRole">
    <div class="ec-categoryNaviRole__inner">

        

        <div class="ec-itemNav">
            <div class="ec-itemNav__heading">Product Category</div>
            <ul class="ec-itemNav__navList">
                <li class="ec-itemNav__navItem" id="1">
                    <span class="ec-itemNav__navItemTitle">
                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_001.jpg" alt="Feedthrough">
                        Feedthrough</span>
                    <div class="ec-itemNav__navItemInner">
                        <div class="ec-itemNav__subnav">
                            <div class="ec-itemNav__subnavFirst is-tree">
                                <div class="ec-itemNav__subnavHeading">
                                    <span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span>
                                    <span class="ec-itemNav__subnavHeadingText">Feedthrough</span>
                                </div>
                                <ul class="ec-itemNav__subnavList">

                                </ul>
                            </div>
                         <div class="ec-itemNav__subnavSecond" id="11"><div class="ec-itemNav__subnavHeading"><span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span><span class="ec-itemNav__subnavHeadingText">Coaxial</span></div><ul class="ec-itemNav__subnavList"></ul></div><div class="ec-itemNav__subnavThird" id="21"><div class="ec-itemNav__subnavHeading"><span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span><span class="ec-itemNav__subnavHeadingText">D-Sub / Micro-D</span></div><ul class="ec-itemNav__subnavList"></ul></div></div>
                    </div>
                </li>
                <li class="ec-itemNav__navItem" id="2">
                    <span class="ec-itemNav__navItemTitle">
                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_002.jpg" alt="Isolator">
                        Isolator</span>
                    <div class="ec-itemNav__navItemInner">
                        <div class="ec-itemNav__subnav">
                            <div class="ec-itemNav__subnavFirst">
                                <div class="ec-itemNav__subnavHeading">
                                    <span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span>
                                    <span class="ec-itemNav__subnavHeadingText">Isolator</span>
                                </div>
                                <ul class="ec-itemNav__subnavList">
                                </ul>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="ec-itemNav__navItem" id="3">
                    <span class="ec-itemNav__navItemTitle">
                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_003.jpg" alt="Viewport">
                        Viewport</span>
                    <div class="ec-itemNav__navItemInner">
                        <div class="ec-itemNav__subnav">
                            <div class="ec-itemNav__subnavFirst is-tree">
                                <div class="ec-itemNav__subnavHeading">
                                    <span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span>
                                    <span class="ec-itemNav__subnavHeadingText">Viewport</span>
                                </div>
                                <ul class="ec-itemNav__subnavList"></ul>
                            </div>
                        <div class="ec-itemNav__subnavSecond" id="175"><div class="ec-itemNav__subnavHeading"><span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span><span class="ec-itemNav__subnavHeadingText">Glass series for NW</span></div><ul class="ec-itemNav__subnavList"></ul></div></div>
                    </div>
                </li>
                <li class="ec-itemNav__navItem" id="4">
                    <span class="ec-itemNav__navItemTitle">
                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_004.jpg" alt="Vacuum Component">
                        Vacuum Component</span>
                    <div class="ec-itemNav__navItemInner">
                        <div class="ec-itemNav__subnav">
                            <div class="ec-itemNav__subnavFirst is-tree">
                                <div class="ec-itemNav__subnavHeading">
                                    <span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span>
                                    <span class="ec-itemNav__subnavHeadingText">Vacuum Component</span>
                                </div>
                                <ul class="ec-itemNav__subnavList"></ul>
                            </div>
                        <div class="ec-itemNav__subnavSecond" id="6"><div class="ec-itemNav__subnavHeading"><span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span><span class="ec-itemNav__subnavHeadingText">Vented Screw</span></div><ul class="ec-itemNav__subnavList"></ul></div><div class="ec-itemNav__subnavThird" id="75"><div class="ec-itemNav__subnavHeading"><span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span><span class="ec-itemNav__subnavHeadingText">Clamp (NW / KF standard)</span></div><ul class="ec-itemNav__subnavList"></ul></div></div>
                    </div>
                </li>
                <li class="ec-itemNav__navItem" id="5">
                    <span class="ec-itemNav__navItemTitle">
                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_005.jpg" alt="Vacuum Valve">
                        Vacuum Valve</span>
                    <div class="ec-itemNav__navItemInner">
                        <div class="ec-itemNav__subnav">
                            <div class="ec-itemNav__subnavFirst">
                                <div class="ec-itemNav__subnavHeading">
                                    <span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span>
                                    <span class="ec-itemNav__subnavHeadingText">Vacuum Valve</span>
                                </div>
                                <ul class="ec-itemNav__subnavList"></ul>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="ec-itemNav__navItem" id="383">
                    <span class="ec-itemNav__navItemTitle">
                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_006.jpg" alt="Motion Feedthroughs">
                        Motion Feedthroughs</span>
                    <div class="ec-itemNav__navItemInner">
                        <div class="ec-itemNav__subnav">
                            <div class="ec-itemNav__subnavFirst">
                                <div class="ec-itemNav__subnavHeading">
                                    <span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span>
                                    <span class="ec-itemNav__subnavHeadingText">Motion Feedthroughs</span>
                                </div>
                                <ul class="ec-itemNav__subnavList"></ul>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="ec-itemNav__navItem" id="7">
                    <span class="ec-itemNav__navItemTitle">
                        <img src="https://static.cosmotec-co.jp/html/template/default/assets/img/product/category_007.jpg" alt="Others">
                        Others</span>
                    <div class="ec-itemNav__navItemInner">
                        <div class="ec-itemNav__subnav">
                            <div class="ec-itemNav__subnavFirst is-tree">
                                <div class="ec-itemNav__subnavHeading">
                                    <span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span>
                                    <span class="ec-itemNav__subnavHeadingText">Others</span>
                                </div>
                                <ul class="ec-itemNav__subnavList"></ul>
                            </div>
                        <div class="ec-itemNav__subnavSecond" id="196"><div class="ec-itemNav__subnavHeading"><span class="ec-itemNav__subnavHeadingPrev"><b aria-hidden="true" class="iconfont iconfont-angle-left"></b></span><span class="ec-itemNav__subnavHeadingText">Ion Pump</span></div><ul class="ec-itemNav__subnavList"></ul></div></div>
                    </div>
                </li>
            </ul>
        </div>
     



        

        <div class="ec-secondaryNav">
            <ul class="ec-secondaryNav__nav">
                                <li class="ec-secondaryNav__navItem">
                    <a href="#shopping/quick">
                        <b aria-hidden="true" class="iconfont iconfont-clock-quick"></b>Quick Order
                    </a>
                </li>

                                <li class="ec-secondaryNav__navItem">
                    <b aria-hidden="true" class="iconfont iconfont-download"></b>CAD · Catalog · Technical Information
                    <b aria-hidden="true" class="iconfont iconfont-angle-down-small"></b>
                    <div class="ec-secondaryNav__subnav">
                        <ul class="ec-secondaryNav__subnavLIst">
                                                        <li class="ec-secondaryNav__subnavItem"><a href="#cad/?utm_source=website&amp;utm_medium=cad&amp;utm_campaign=cad">CAD Download</a></li>
                                                        <li class="ec-secondaryNav__subnavItem"><a href="#info/catalog/?utm_source=website&amp;utm_medium=catalog&amp;utm_campaign=catalog">Catalog Download</a></li>
                                                        <li class="ec-secondaryNav__subnavItem"><a href="#info/%e6%8a%80%e8%a1%93%e6%83%85%e5%a0%b1-2/">Technical Data</a></li>
                                                        <li class="ec-secondaryNav__subnavItem"><a href="#info/movie/">Movie</a></li>
                        </ul>
                    </div>
                </li>

                                <li class="ec-secondaryNav__navItem">
                    <b aria-hidden="true" class="iconfont iconfont-building"></b>About Us
                    <b aria-hidden="true" class="iconfont iconfont-angle-down-small"></b>
                    <div class="ec-secondaryNav__subnav">
                        <ul class="ec-secondaryNav__subnavList">
                                                        <li class="ec-secondaryNav__subnavItem"><a href="#info/corporate/#data">Company Profile</a></li>
                                                        <li class="ec-secondaryNav__subnavItem"><a href="#info/corporate/#access">Office</a></li>
                                                        <li class="ec-secondaryNav__subnavItem"><a href="#info/client/">Major Customers</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>