<?php
/** @var $block \Cosmotec\ProductView\Block\BasicInformation */
$product = $block->getProduct();
?>

 

    <?php /* if ($product): ?>
        <p><strong>SKU:</strong> <?= $block->escapeHtml($product->getSku()) ?></p>
        <p><strong>Name:</strong> <?= $block->escapeHtml($product->getName()) ?></p>
    <?php endif;*/ ?>
 

 <div class="basic-info-table-wraper">
<table class="basic-info-table" width="100%">
                        <thead>
                        <tr>
                                                        <th colspan="2">Basic Information</th>
                        </tr>
                        </thead>
                        <tbody>
                                                    <tr>
                                                                <th>type</th>
                                                                <td>BNC</td>
                            </tr>
                                                    <tr>
                                                                <th>Connection type</th>
                                                                <td>The atmosphere-side plug-fitti</td>
                            </tr>
                                                    <tr>
                                                                <th>electrode</th>
                                                                <td>Kovar ®</td>
                            </tr>
                                                    <tr>
                                                                <th>Flange material</th>
                                                                <td>SUS 304</td>
                            </tr>
                                                    <tr>
                                                                <th>sleeve</th>
                                                                <td>Kovar ®</td>
                            </tr>
                                                    <tr>
                                                                <th>Insulator</th>
                                                                <td>Alumina ceramic</td>
                            </tr>
                                                    <tr>
                                                                <th>Maximum temperature</th>
                                                                <td>450℃</td>
                            </tr>
                                                    <tr>
                                                                <th>The lowest temperature</th>
                                                                <td>-196℃</td>
                            </tr>
                                                    <tr>
                                                                <th>Leak rate</th>
                                                                <td>&lt;1.3x10<sup>-10</sup>Pa･㎥/sec</td>
                            </tr>
                                                    <tr>
                                                                <th>Classification</th>
                                                                <td>Flanged terminal</td>
                            </tr>
                                                    <tr>
                                                                <th>type</th>
                                                                <td>Ground shield</td>
                            </tr>
                                                    <tr>
                                                                <th>Impedance</th>
                                                                <td>50 Ω</td>
                            </tr>
                                                    <tr>
                                                                <th>Insulation resistance value</th>
                                                                <td>10⁹ ohm</td>
                            </tr>
                                                    <tr>
                                                                <th>frequency</th>
                                                                <td>100 MHz</td>
                            </tr>
                                                    <tr>
                                                                <th>Withstand voltage: DC</th>
                                                                <td>1 kV</td>
                            </tr>
                                                    <tr>
                                                                <th>Electric current / 1 pc.</th>
                                                                <td>3 A</td>
                            </tr>
                                                    <tr>
                                                                <th>RoHS2 corresponding</th>
                                                                <td>○</td>
                            </tr>
                                                </tbody>
                    </table>
</div>
    <!-- https://en.cosmotec-co.jp/contact?id=1&amp;quote=item -->
 

    <div class="simple-product-contact inquiry-box">
        <div class="info-line-1">
            <a href="void:javascript()" class="inquiry-btn  action contact">
                <span>Inquiry for this subcategory</span>
            </a>
        </div>
    </div>