<?php
/** @var $block \Cosmotec\ProductView\Block\Product\Simple */
$product = $block->getProduct();
?>

<?php  if ($product): ?>
    <div class="simple-product-stockinfo">
        <div class="info-line-1">
            <span class="stock-label"><?= $escaper->escapeHtml(__('Stock')) ?></span>
            <span  class="stock-qty"><?= $block->escapeHtml($product->getSku()) ?></span>
            <span  class="stock-delivery"><?= $block->escapeHtml($product->getStockDelivery()) ?>1-2 Business Days</span>
        </div>
        <div class="info-line-2">
        <span class="stock-when-out-of-stock-label"><?= $escaper->escapeHtml(__('When out of stock')) ?></span>
        <span  class="stock-when-out-of-stock"><?= $block->escapeHtml($block->getChildAttributeLabel($product, 'ct_when_out_of_stock')) ?></span>

        </div>
    </div>
<?php endif; ?>
