<div class="ec-layoutRole__footerWrap" id="ec-layoutRole__footerWrap">
    <div class="ec-layoutRole__footerWrapInner">

        <div class="ec-blockTopBtnWrap" id="ec-blockTopBtnWrap" style="bottom: -20px;">
            <div class="ec-blockTopBtn" id="ec-blockTopBtn" style="margin-bottom: 40px;"><b aria-hidden="true" class="iconfont iconfont-top"></b></div>
        </div>

        <div class="ec-appealThatday">
            <div class="ec-appealThatdayInner">
                Shipping accepted on the day on orders until 17:00
                <span class="ec-appealThatdaySub">Hours 9:00 to 18:00 except Saturdays, Sundays, and holidays</span>
            </div>
        </div>

        <div class="ec-footerContact">
            <div class="ec-footerContact__head">Contact Us</div>
            <div class="ec-footerContact__lead">
                Please fill in the form below.<br>
After confirming the content of your enquiry,<br>
a representative will contact you.<br>

            </div>
            <ul class="ec-footerContact__list">
                <li class="ec-footerContact__tel">
                    <div class="ec-footerContact__telHead">
                        <b aria-hidden="true" class="iconfont iconfont-phone-volume"></b>
                        <div class="ec-footerContact__telHeadInner">
                            Contact by Phone
                            <span class="ec-footerContact__telHeadSub">(Reception time weekdays 9:00 to 18:00)</span>
                        </div>
                    </div>
                    <div class="ec-footerContact__telNum">
                        <a href="tel:0332705761" class="ec-footerContact__telNumLink">
                            <span class="ec-footerContact__telNumSub">Tokyo Office</span>
                            03-3270-5761
                            <b aria-hidden="true" class="iconfont iconfont-angle-right"></b>
                        </a>
                    </div>
                    <div class="ec-footerContact__telNum">
                        <a href="tel:0661314751" class="ec-footerContact__telNumLink">
                            <span class="ec-footerContact__telNumSub">Osaka Office</span>
                            06-6131-4751
                            <b aria-hidden="true" class="iconfont iconfont-angle-right"></b>
                        </a>
                    </div>
                    <div class="ec-footerContact__telText">
                        Contact by Phone(Weekdays 9:00 to 18:00)
                    </div>
                </li>
                <li class="ec-footerContact__mail">
                    <a href="#contact" class="ec-footerContact__mailLink">
                        <b aria-hidden="true" class="iconfont iconfont-comment-dots"></b>
                        Contact Us
                        <b aria-hidden="true" class="iconfont iconfont-angle-right"></b>
                    </a>
                </li>
            </ul>
        </div>

        <div class="ec-layoutRole__footerMenu">
            <nav>
                <div class="ec-footerMenuRole">
                    <div class="ec-footerMenuRole__product">
                        <div class="ec-footerMenu">
                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                                                        <a href="#1">Feedthrough</a>
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#11">Coaxial</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#19">Multi-pin</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#35">Thermocouple</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#48">High voltage and Small middle and High current</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#56">Optical Fiber</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#59">PAVE Product</a></li>
                                    </ul>
                                </li>
                            </ul>

                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                                                        <a href="#2">Isolator</a>
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#60">Tube end</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#61">Swagelok® Standard</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#62">VCR® Standard</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#63">NW / KF Standard</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#64">ICF Standard</a></li>
                                    </ul>
                                </li>
                            </ul>

                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                                                        <a href="#3">Viewport</a>
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#65">Borosilicate</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#66">Sapphire (Al2O3)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#67">Quartz (SiO2)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#69">Calcium Fluoride (CaF2)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#70">Borosilicate + lead glass</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#72">Viewport Cover</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#73">Viewport Shutter</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                        <div class="ec-footerMenu">
                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                                                        <a href="#4">Vacuum Component</a>
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#74">Clamp / Bolt</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#85">Gasket / Center ring / O-ring</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#96">Blank Flange / Flange with Pipe</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#108">Various Vacuum Components (Standard Conversion, Size Conversion etc)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#130">Flexible Tube / Bellows</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#133">Vacuum Exhaust Hose</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#147">Valve / Leak Port (Leak Valve)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#150">Water-Cooled, Gas, and Liquid Nitrogen Introduction Flange</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#160">CeFiX® System</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#184">Dual Edge Radial Port</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#185">Multi-Port Flange</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#186">Zero-Length Conversion Fange</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                        <div class="ec-footerMenu">
                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                                                        <a href="#5">Vacuum Valve</a>
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#188">Vacuum Valve (NW / KF Standard)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#189">Vacuum Valve (ICF Standard)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#190">Leak Port (NW / KF Standard)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#191">Leak Port (ICF Standard)</a></li>
                                    </ul>
                                </li>
                            </ul>

                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                                                        <a href="#6">Vented Screw</a>
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#192">Bolt (precision cleaned)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#193">Nut (precision cleaned)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#194">Washers (precision cleaned)</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#195">O-ring (precision cleaned / pre-baking)</a></li>
                                    </ul>
                                </li>
                            </ul>

                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                                                        <a href="#7">Others</a>
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#196">Ion Pump</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#202">Crystal Oscillator</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#203">Sapphire Substrate</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#205">SUS Tubing</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#206">Tools and Bencot, Gloves, such as Consumables</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="ec-footerMenuRole__guide">
                        <div class="ec-footerMenu">
                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                    <span class="ec-footerMenu__itemToggle is-active">Customer Service</span>
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#guide/">User Guide</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#faq/">FAQ</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#customize/">Customize Services</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                        <div class="ec-footerMenu">
                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item"><a href="#corporate/#data">Company Profile</a></li>
                            </ul>
                        </div>

                        <div class="ec-footerMenu">
                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item"><a href="#case/">Example</a></li>
                            </ul>
                        </div>

                        <div class="ec-footerMenu--pc">
                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                    Customer Service
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#guide/">User Guide</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#faq/">FAQ</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#cad/">CAD Download</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#catalog/">Catalog Download</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#info/%e6%8a%80%e8%a1%93%e6%83%85%e5%a0%b1-2/">Technical Data</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#shopping/quick">Quick Order</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#customize/">Customize Services</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#case/">Example</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#movie/">MOVIE</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                        <div class="ec-footerMenu--pc">
                            <ul class="ec-footerMenu__list">
                                <li class="ec-footerMenu__item">
                                    About Us
                                    <ul class="ec-footerMenu__list--sub">
                                        <li class="ec-footerMenu__item--sub"><a href="#corporate/#greet">Greeting</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#corporate/#data">Company Profile</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#corporate/#history">Corporate History</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#corporate/#philosophy">Corporate Philosophy</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#corporate/#access">Office</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#corporate/#recruit">Recruit</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#client/">Major Customers</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#news/">NEWS</a></li>
                                        <li class="ec-footerMenu__item--sub"><a href="#dictionary/">Vacuum Glossary</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

    </div>

    <div class="ec-layoutRole__footer">
        <footer>
            <div class="ec-footerRole">
                <div class="ec-footerRole__inner">
                    <div class="ec-footerNavi__wrap">
                        <ul class="ec-footerNavi">
                            <li class="ec-footerNavi__link"><a href="#privacy/">Privacy Policy</a></li>
                            <li class="ec-footerNavi__link"><a href="#agreement/">Terms of Service</a></li>
                            <li class="ec-footerNavi__link"><a href="#law/">Notation based on the Act on Specified Commercial Transactions</a></li>
                            <li class="ec-footerNavi__link"><a href="#about/">About This Website</a></li>
                            <li class="ec-footerNavi__link"><a href="#sitemap/">Site Map</a></li>
                        </ul>
                        <button type="button" class="ec-footerNavi__device ec-switch-sp is-hidden">Display Mode： SP site</button>
                        <button type="button" class="ec-footerNavi__device ec-switch-pc is-hidden">Display Mode： PC</button>
                        <div class="ec-footerNavi__language">
                            <span>Language：</span>
                            <select class="ec-footerNavi__select js-change-locale" data-sys-env="prod">
                                                                <option value="ja">Japanese</option>
                                <option value="en">English</option>
                                                            </select>
                        </div>
                    </div>
                    <div class="ec-footerCopyright"><small>Copyright©COSMOTEC Corporation.All rights reserved.</small></div>
                </div>
            </div>
        </footer>
    </div>

</div>