<div class="ec-productLink__part">
                <div class="ec-productLink__heading">Connection parts</div>
                <div class="ec-productRole">
                    <div class="ec-product__row">
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__imgWrap">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    Same day shipping is possible
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#82/product_id/766">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/10152_p-150-150-64e6dfc339785.jpg" alt="Push-on type 10 pieces for connecting parts vacuum side socket contacts φ2.4">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="ec-product__description">
                                        <div class="ec-product__name">
                                            <a href="#82/product_id/766">
                                                                                                Push-on type 10 pieces for connecting parts vacuum side socket contacts φ2.4
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :10152<br>
                                                                                        Model:SVC24S
                                        </div>
                                                                                                                            <div class="ec-product__price">
                                                                                                                                                    17,700JPY
                                                    (with tax 19,470JPY)
                                                                                            </div>
                                                                            </div>
                                </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__imgWrap">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    Same day shipping is possible
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#82/product_id/767">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14427_p-150-150-5d4d225b13686-767.jpg" alt="Vacuum side socket contact crimp type Fai2.4 1 pcs">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="ec-product__description">
                                        <div class="ec-product__name">
                                            <a href="#82/product_id/767">
                                                                                                Vacuum side socket contact crimp type Fai2.4 1 pcs
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :14427<br>
                                                                                        Model:SVC24CU
                                        </div>
                                                                                                                            <div class="ec-product__price">
                                                                                                                                                    4,700JPY
                                                    (with tax 5,170JPY)
                                                                                            </div>
                                                                            </div>
                                </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__imgWrap">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    Same day shipping is possible
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#32/product_id/773">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14431_p-150-150-5d4d225b13686-773.jpg" alt="Connection parts Vacuum side Cable with one side connector for BNC-R/BNC-R-F L=1000">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="ec-product__description">
                                        <div class="ec-product__name">
                                            <a href="#32/product_id/773">
                                                                                                Connection parts Vacuum side Cable with one side connector for BNC-R/BNC-R-F L=1000
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :14431<br>
                                                                                        Model:VCK1000X/BJ
                                        </div>
                                                                                                                            <div class="ec-product__price">
                                                                                                                                                    31,100JPY
                                                    (with tax 34,210JPY)
                                                                                            </div>
                                                                            </div>
                                </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__imgWrap">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    Same day shipping is possible
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#34/product_id/797">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/10017_p-150-150-5d4d225b13686-797.jpg" alt="For connecting parts atmosphere side plug BNC">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="ec-product__description">
                                        <div class="ec-product__name">
                                            <a href="#34/product_id/797">
                                                                                                For connecting parts atmosphere side plug BNC
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :10017<br>
                                                                                        Model:ASP-BNC
                                        </div>
                                                                                                                            <div class="ec-product__price">
                                                                                                                                                    700JPY
                                                    (with tax 770JPY)
                                                                                            </div>
                                                                            </div>
                                </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__imgWrap">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    Same day shipping is possible
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#30/product_id/764">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14428_p-150-150-5d4d225b13686-764.jpg" alt="Connection piece vacuum side Kapton coated cables AWG # for 26 coaxial L = 1000">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="ec-product__description">
                                        <div class="ec-product__name">
                                            <a href="#30/product_id/764">
                                                                                                Connection piece vacuum side Kapton coated cables AWG # for 26 coaxial L = 1000
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :14428<br>
                                                                                        Model:VCK1000/XX
                                        </div>
                                                                                                                            <div class="ec-product__price">
                                                                                                                                                    13,700JPY
                                                    (with tax 15,070JPY)
                                                                                            </div>
                                                                            </div>
                                </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__imgWrap">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    Same day shipping is possible
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#30/product_id/765">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14429_p-150-150-5d4d225b13686-765.jpg" alt="Connecting parts Vacuum side PEEK coated cable AWG#28 For coaxial L=1000">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="ec-product__description">
                                        <div class="ec-product__name">
                                            <a href="#30/product_id/765">
                                                                                                Connecting parts Vacuum side PEEK coated cable AWG#28 For coaxial L=1000
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :14429<br>
                                                                                        Model:VCP1000/XX
                                        </div>
                                                                                                                            <div class="ec-product__price">
                                                                                                                                                    3,900JPY
                                                    (with tax 4,290JPY)
                                                                                            </div>
                                                                            </div>
                                </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__imgWrap">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    Same day shipping is possible
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#33/product_id/788">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14447_p-150-150-5d4d225b13686-788.jpg" alt="For connecting parts air-side cable BNC 3D-2V L = 1000">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="ec-product__description">
                                        <div class="ec-product__name">
                                            <a href="#33/product_id/788">
                                                                                                For connecting parts air-side cable BNC 3D-2V L = 1000
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :14447<br>
                                                                                        Model:ACV1000B/XX
                                        </div>
                                                                                                                            <div class="ec-product__price">
                                                                                                                                                    300JPY
                                                    (with tax 330JPY)
                                                                                            </div>
                                                                            </div>
                                </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__imgWrap">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    Same day shipping is possible
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#35/product_id/806">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14456_p-150-150-5d4d225b13686-806.jpg" alt="Connection parts atmosphere side both sides with a plug cable BNC for L = 1000">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="ec-product__description">
                                        <div class="ec-product__name">
                                            <a href="#35/product_id/806">
                                                                                                Connection parts atmosphere side both sides with a plug cable BNC for L = 1000
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :14456<br>
                                                                                        Model:ACV1000BP/BP
                                        </div>
                                                                                                                            <div class="ec-product__price">
                                                                                                                                                    2,600JPY
                                                    (with tax 2,860JPY)
                                                                                            </div>
                                                                            </div>
                                </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__imgWrap">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    Same day shipping is possible
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#35/product_id/807">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14457_p-150-150-5d4d225b13686-807.jpg" alt="Connection parts atmosphere side one side plug cable with BNC for L = 1000">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="ec-product__description">
                                        <div class="ec-product__name">
                                            <a href="#35/product_id/807">
                                                                                                Connection parts atmosphere side one side plug cable with BNC for L = 1000
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :14457<br>
                                                                                        Model:ACV1000X/BP
                                        </div>
                                                                                                                            <div class="ec-product__price">
                                                                                                                                                    1,800JPY
                                                    (with tax 1,980JPY)
                                                                                            </div>
                                                                            </div>
                                </div>
                            </div>
                                            </div>
                </div>
            </div>