<div class="ec-productLink__relation">
                <div class="ec-productLink__heading">Related products</div>
                <div class="ec-productRole">
                    <div class="ec-product__row">
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__description">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    1-2 Business Days
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#220/product_id/18016">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/24043_p-150-150-6229954b3b232.jpg" alt="NW50 Clamp 2-point type">
                                            </a>
                                        </div>
                                        <div class="ec-product__name">
                                            <a href="#220/product_id/18016">
                                                                                                NW50 Clamp 2-point type
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :24043<br>
                                                                                        Model:NW50CWA
                                        </div>
                                    </div>
                                                                                                                <div class="ec-product__price">
                                                                                                                                        1,700JPY
                                                (with tax 1,870JPY)
                                                                                    </div>
                                                                    </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__description">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    1-2 Business Days
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#249/product_id/24671">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/20156_p-150-150-6504079dcc4c5.jpg" alt="NW50 Center Ring SUS/Viton">
                                            </a>
                                        </div>
                                        <div class="ec-product__name">
                                            <a href="#249/product_id/24671">
                                                                                                NW50 Center Ring SUS/Viton
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :25525<br>
                                                                                        Model:NW50CRSVA
                                        </div>
                                    </div>
                                                                                                                <div class="ec-product__price">
                                                                                                                                        2,700JPY
                                                (with tax 2,970JPY)
                                                                                    </div>
                                                                    </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__description">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    1-2 Business Days
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#30/product_id/764">
                                                 <img src="https://static.cosmotec-co.jp/html/upload/save_image/14428_p-150-150-5d4d225b13686-764.jpg" alt="Connection piece vacuum side Kapton coated cables AWG # for 26 coaxial L = 1000">
                                            </a>
                                        </div>
                                        <div class="ec-product__name">
                                            <a href="#30/product_id/764">
                                                                                                Connection piece vacuum side Kapton coated cables AWG # fo...</a></div>
                                        <div class="ec-product__code">
                                                                                        Product code :14428<br>
                                                                                        Model:VCK1000/XX
                                        </div>
                                    </div>
                                                                                                                <div class="ec-product__price">
                                                                                                                                        13,700JPY
                                                (with tax 15,070JPY)
                                                                                    </div>
                                                                    </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__description">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    1-2 Business Days
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#30/product_id/765">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14429_p-150-150-5d4d225b13686-765.jpg" alt="Connecting parts Vacuum side PEEK coated cable AWG#28 For coaxial L=1000">
                                            </a>
                                        </div>
                                        <div class="ec-product__name">
                                            <a href="#30/product_id/765">
                                                                                                Connecting parts Vacuum side PEEK coated cable AWG#28 F...</a></div>
                                        <div class="ec-product__code">
                                                                                        Product code :14429<br>
                                                                                        Model:VCP1000/XX
                                        </div>
                                    </div>
                                                                                                                <div class="ec-product__price">
                                                                                                                                        3,900JPY
                                                (with tax 4,290JPY)
                                                                                    </div>
                                                                    </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__description">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    1-2 Business Days
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#33/product_id/788">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14447_p-150-150-5d4d225b13686-788.jpg" alt="For connecting parts air-side cable BNC 3D-2V L = 1000">
                                            </a>
                                        </div>
                                        <div class="ec-product__name">
                                            <a href="#33/product_id/788">
                                                                                                For connecting parts air-side cable BNC 3D-2V L = 1000
                                            </a>
                                        </div>
                                        <div class="ec-product__code">
                                                                                        Product code :14447<br>
                                                                                        Model:ACV1000B/XX
                                        </div>
                                    </div>
                                                                                                                <div class="ec-product__price">
                                                                                                                                        300JPY
                                                (with tax 330JPY)
                                                                                    </div>
                                                                    </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__description">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    1-2 Business Days
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#35/product_id/806">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14456_p-150-150-5d4d225b13686-806.jpg" alt="Connection parts atmosphere side both sides with a plug cable BNC for L = 1000">
                                            </a>
                                        </div>
                                        <div class="ec-product__name">
                                            <a href="#35/product_id/806">
                                                                                                Connection parts atmosphere side both sides with a plug cable ...</a></div>
                                        <div class="ec-product__code">
                                                                                        Product code :14456<br>
                                                                                        Model:ACV1000BP/BP
                                        </div>
                                    </div>
                                                                                                                <div class="ec-product__price">
                                                                                                                                        2,600JPY
                                                (with tax 2,860JPY)
                                                                                    </div>
                                                                    </div>
                            </div>
                                                    <div class="ec-product__list">
                                <div class="ec-product__inner">
                                    <div class="ec-product__description">
                                                                                                                                                                                                                            <div class="ec-statusLabel ec-label--quaternary">
                                                    1-2 Business Days
                                                </div>
                                                                                    
                                        <div class="ec-product__img">
                                            <a href="#35/product_id/807">
                                                                                                <img src="https://static.cosmotec-co.jp/html/upload/save_image/14457_p-150-150-5d4d225b13686-807.jpg" alt="Connection parts atmosphere side one side plug cable with BNC for L = 1000">
                                            </a>
                                        </div>
                                        <div class="ec-product__name">
                                            <a href="#35/product_id/807">
                                                                                                Connection parts atmosphere side one side plug cable with B...</a></div>
                                        <div class="ec-product__code">
                                                                                        Product code :14457<br>
                                                                                        Model:ACV1000X/BP
                                        </div>
                                    </div>
                                                                                                                <div class="ec-product__price">
                                                                                                                                        1,800JPY
                                                (with tax 1,980JPY)
                                                                                    </div>
                                                                    </div>
                            </div>
                                            </div>
                </div>
            </div>